INSERT INTO TB_PRODUTO (nome, descricao, preco) VALUES ('Pao Frances', 'Pãozinho quentinho', 0.5);
INSERT INTO TB_PRODUTO (nome, descricao, preco) VALUES ('Manteira', 'Qually Com Sal', '7.5');
INSERT INTO TB_PRODUTO (nome, descricao, preco) VALUES ('Mortandela Defumada', 'Mortandela Defumada Fatiada', '0.5');
INSERT INTO TB_PRODUTO (nome, descricao, preco) VALUES ('Queijo Mussarela', 'Queijo Mussarela Fatiado', '0.5');
INSERT INTO TB_CLIENTE (nome, cpf, telefone, email, user_name, senha, endereco) VALUES ('Samuel','111.222.070-99','67 99999-0000','samuel@gmail.com','samuel190','123456', 'AV. Dourados, 111');
INSERT INTO TB_ATENDENTE (nome, cpf, telefone, email, user_name, senha) VALUES ('Samuel','111.222.070-99','67 99999-0000','samuel@gmail.com','samuel190','123456');
INSERT INTO TB_ATENDENTE (nome, cpf, telefone, email, user_name, senha) VALUES  ('Gabriel','111.333.060-99','67 99999-0011','gabriel@gmail.com','gabriel190','000000');
INSERT INTO TB_VENDA (pagamento, id_atendente_fk) VALUES ('PIX', 1 );
INSERT INTO TB_VENDA (pagamento, id_atendente_fk) VALUES ('CARTAODEBITO', 2);
INSERT INTO TB_VENDA (pagamento, id_atendente_fk) VALUES ('CARTAOCREDITO', 2);
INSERT INTO TB_VENDA (pagamento, id_atendente_fk) VALUES ('AVISTA', 1); 
INSERT INTO TB_ITEM_VENDA (quantidade, id_produto_fk) values ('5', 2);
